/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedPasswortAendernRouteImport } from './routes/_authenticated/passwort-aendern'
import { Route as AuthenticatedAppSzenarioRouteImport } from './routes/_authenticated/_app/szenario'
import { Route as AuthenticatedAppUebersichtRouteImport } from './routes/_authenticated/_app/uebersicht'
import { Route as AuthenticatedAppVerkaufsmengenRouteImport } from './routes/_authenticated/_app/verkaufsmengen'
import { Route as AuthenticatedAppEinstellungenIndexRouteImport } from './routes/_authenticated/_app/einstellungen/index'
import { Route as AuthenticatedAppEinstellungenBenutzerRouteImport } from './routes/_authenticated/_app/einstellungen/benutzer'
import { Route as AuthenticatedAppEinstellungenKonfigurationRouteImport } from './routes/_authenticated/_app/einstellungen/konfiguration'
import { Route as AuthenticatedAppGerichteIndexRouteImport } from './routes/_authenticated/_app/gerichte.index'
import { Route as AuthenticatedAppGerichteDishIdRouteImport } from './routes/_authenticated/_app/gerichte.$dishId'
import { Route as AuthenticatedAppSpeisekartenIndexRouteImport } from './routes/_authenticated/_app/speisekarten.index'
import { Route as AuthenticatedAppSpeisekartenMenuCardIdRouteImport } from './routes/_authenticated/_app/speisekarten.$menuCardId'
import { Route as AuthenticatedAppSpeisekartenImportierenRouteImport } from './routes/_authenticated/_app/speisekarten.importieren'
import { Route as AuthenticatedAppZutatenIndexRouteImport } from './routes/_authenticated/_app/zutaten.index'
import { Route as AuthenticatedAppZutatenImportierenRouteImport } from './routes/_authenticated/_app/zutaten.importieren'
import { Route as AuthenticatedAppGerichteAddOnsIndexRouteImport } from './routes/_authenticated/_app/gerichte.add-ons.index'
import { Route as AuthenticatedAppGerichteAddOnsAddOnIdRouteImport } from './routes/_authenticated/_app/gerichte.add-ons.$addOnId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasswortAendernRoute =
  AuthenticatedPasswortAendernRouteImport.update({
    id: '/passwort-aendern',
    path: '/passwort-aendern',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSzenarioRoute =
  AuthenticatedAppSzenarioRouteImport.update({
    id: '/szenario',
    path: '/szenario',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppUebersichtRoute =
  AuthenticatedAppUebersichtRouteImport.update({
    id: '/uebersicht',
    path: '/uebersicht',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppVerkaufsmengenRoute =
  AuthenticatedAppVerkaufsmengenRouteImport.update({
    id: '/verkaufsmengen',
    path: '/verkaufsmengen',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEinstellungenIndexRoute =
  AuthenticatedAppEinstellungenIndexRouteImport.update({
    id: '/einstellungen/',
    path: '/einstellungen/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEinstellungenBenutzerRoute =
  AuthenticatedAppEinstellungenBenutzerRouteImport.update({
    id: '/einstellungen/benutzer',
    path: '/einstellungen/benutzer',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEinstellungenKonfigurationRoute =
  AuthenticatedAppEinstellungenKonfigurationRouteImport.update({
    id: '/einstellungen/konfiguration',
    path: '/einstellungen/konfiguration',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGerichteIndexRoute =
  AuthenticatedAppGerichteIndexRouteImport.update({
    id: '/gerichte/',
    path: '/gerichte/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGerichteDishIdRoute =
  AuthenticatedAppGerichteDishIdRouteImport.update({
    id: '/gerichte/$dishId',
    path: '/gerichte/$dishId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSpeisekartenIndexRoute =
  AuthenticatedAppSpeisekartenIndexRouteImport.update({
    id: '/speisekarten/',
    path: '/speisekarten/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSpeisekartenMenuCardIdRoute =
  AuthenticatedAppSpeisekartenMenuCardIdRouteImport.update({
    id: '/speisekarten/$menuCardId',
    path: '/speisekarten/$menuCardId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSpeisekartenImportierenRoute =
  AuthenticatedAppSpeisekartenImportierenRouteImport.update({
    id: '/speisekarten/importieren',
    path: '/speisekarten/importieren',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppZutatenIndexRoute =
  AuthenticatedAppZutatenIndexRouteImport.update({
    id: '/zutaten/',
    path: '/zutaten/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppZutatenImportierenRoute =
  AuthenticatedAppZutatenImportierenRouteImport.update({
    id: '/zutaten/importieren',
    path: '/zutaten/importieren',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGerichteAddOnsIndexRoute =
  AuthenticatedAppGerichteAddOnsIndexRouteImport.update({
    id: '/gerichte/add-ons/',
    path: '/gerichte/add-ons/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGerichteAddOnsAddOnIdRoute =
  AuthenticatedAppGerichteAddOnsAddOnIdRouteImport.update({
    id: '/gerichte/add-ons/$addOnId',
    path: '/gerichte/add-ons/$addOnId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/szenario': typeof AuthenticatedAppSzenarioRoute
  '/uebersicht': typeof AuthenticatedAppUebersichtRoute
  '/verkaufsmengen': typeof AuthenticatedAppVerkaufsmengenRoute
  '/einstellungen/benutzer': typeof AuthenticatedAppEinstellungenBenutzerRoute
  '/einstellungen/konfiguration': typeof AuthenticatedAppEinstellungenKonfigurationRoute
  '/gerichte/$dishId': typeof AuthenticatedAppGerichteDishIdRoute
  '/speisekarten/$menuCardId': typeof AuthenticatedAppSpeisekartenMenuCardIdRoute
  '/speisekarten/importieren': typeof AuthenticatedAppSpeisekartenImportierenRoute
  '/zutaten/importieren': typeof AuthenticatedAppZutatenImportierenRoute
  '/einstellungen/': typeof AuthenticatedAppEinstellungenIndexRoute
  '/gerichte/': typeof AuthenticatedAppGerichteIndexRoute
  '/speisekarten/': typeof AuthenticatedAppSpeisekartenIndexRoute
  '/zutaten/': typeof AuthenticatedAppZutatenIndexRoute
  '/gerichte/add-ons/$addOnId': typeof AuthenticatedAppGerichteAddOnsAddOnIdRoute
  '/gerichte/add-ons/': typeof AuthenticatedAppGerichteAddOnsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/szenario': typeof AuthenticatedAppSzenarioRoute
  '/uebersicht': typeof AuthenticatedAppUebersichtRoute
  '/verkaufsmengen': typeof AuthenticatedAppVerkaufsmengenRoute
  '/einstellungen/benutzer': typeof AuthenticatedAppEinstellungenBenutzerRoute
  '/einstellungen/konfiguration': typeof AuthenticatedAppEinstellungenKonfigurationRoute
  '/gerichte/$dishId': typeof AuthenticatedAppGerichteDishIdRoute
  '/speisekarten/$menuCardId': typeof AuthenticatedAppSpeisekartenMenuCardIdRoute
  '/speisekarten/importieren': typeof AuthenticatedAppSpeisekartenImportierenRoute
  '/zutaten/importieren': typeof AuthenticatedAppZutatenImportierenRoute
  '/einstellungen': typeof AuthenticatedAppEinstellungenIndexRoute
  '/gerichte': typeof AuthenticatedAppGerichteIndexRoute
  '/speisekarten': typeof AuthenticatedAppSpeisekartenIndexRoute
  '/zutaten': typeof AuthenticatedAppZutatenIndexRoute
  '/gerichte/add-ons/$addOnId': typeof AuthenticatedAppGerichteAddOnsAddOnIdRoute
  '/gerichte/add-ons': typeof AuthenticatedAppGerichteAddOnsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/_authenticated/_app/szenario': typeof AuthenticatedAppSzenarioRoute
  '/_authenticated/_app/uebersicht': typeof AuthenticatedAppUebersichtRoute
  '/_authenticated/_app/verkaufsmengen': typeof AuthenticatedAppVerkaufsmengenRoute
  '/_authenticated/_app/einstellungen/benutzer': typeof AuthenticatedAppEinstellungenBenutzerRoute
  '/_authenticated/_app/einstellungen/konfiguration': typeof AuthenticatedAppEinstellungenKonfigurationRoute
  '/_authenticated/_app/gerichte/$dishId': typeof AuthenticatedAppGerichteDishIdRoute
  '/_authenticated/_app/speisekarten/$menuCardId': typeof AuthenticatedAppSpeisekartenMenuCardIdRoute
  '/_authenticated/_app/speisekarten/importieren': typeof AuthenticatedAppSpeisekartenImportierenRoute
  '/_authenticated/_app/zutaten/importieren': typeof AuthenticatedAppZutatenImportierenRoute
  '/_authenticated/_app/einstellungen/': typeof AuthenticatedAppEinstellungenIndexRoute
  '/_authenticated/_app/gerichte/': typeof AuthenticatedAppGerichteIndexRoute
  '/_authenticated/_app/speisekarten/': typeof AuthenticatedAppSpeisekartenIndexRoute
  '/_authenticated/_app/zutaten/': typeof AuthenticatedAppZutatenIndexRoute
  '/_authenticated/_app/gerichte/add-ons/$addOnId': typeof AuthenticatedAppGerichteAddOnsAddOnIdRoute
  '/_authenticated/_app/gerichte/add-ons/': typeof AuthenticatedAppGerichteAddOnsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/passwort-aendern'
    | '/szenario'
    | '/uebersicht'
    | '/verkaufsmengen'
    | '/einstellungen/benutzer'
    | '/einstellungen/konfiguration'
    | '/gerichte/$dishId'
    | '/speisekarten/$menuCardId'
    | '/speisekarten/importieren'
    | '/zutaten/importieren'
    | '/einstellungen/'
    | '/gerichte/'
    | '/speisekarten/'
    | '/zutaten/'
    | '/gerichte/add-ons/$addOnId'
    | '/gerichte/add-ons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/passwort-aendern'
    | '/szenario'
    | '/uebersicht'
    | '/verkaufsmengen'
    | '/einstellungen/benutzer'
    | '/einstellungen/konfiguration'
    | '/gerichte/$dishId'
    | '/speisekarten/$menuCardId'
    | '/speisekarten/importieren'
    | '/zutaten/importieren'
    | '/einstellungen'
    | '/gerichte'
    | '/speisekarten'
    | '/zutaten'
    | '/gerichte/add-ons/$addOnId'
    | '/gerichte/add-ons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/_app'
    | '/_authenticated/passwort-aendern'
    | '/_authenticated/_app/szenario'
    | '/_authenticated/_app/uebersicht'
    | '/_authenticated/_app/verkaufsmengen'
    | '/_authenticated/_app/einstellungen/benutzer'
    | '/_authenticated/_app/einstellungen/konfiguration'
    | '/_authenticated/_app/gerichte/$dishId'
    | '/_authenticated/_app/speisekarten/$menuCardId'
    | '/_authenticated/_app/speisekarten/importieren'
    | '/_authenticated/_app/zutaten/importieren'
    | '/_authenticated/_app/einstellungen/'
    | '/_authenticated/_app/gerichte/'
    | '/_authenticated/_app/speisekarten/'
    | '/_authenticated/_app/zutaten/'
    | '/_authenticated/_app/gerichte/add-ons/$addOnId'
    | '/_authenticated/_app/gerichte/add-ons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passwort-aendern': {
      id: '/_authenticated/passwort-aendern'
      path: '/passwort-aendern'
      fullPath: '/passwort-aendern'
      preLoaderRoute: typeof AuthenticatedPasswortAendernRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/szenario': {
      id: '/_authenticated/_app/szenario'
      path: '/szenario'
      fullPath: '/szenario'
      preLoaderRoute: typeof AuthenticatedAppSzenarioRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/uebersicht': {
      id: '/_authenticated/_app/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof AuthenticatedAppUebersichtRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/verkaufsmengen': {
      id: '/_authenticated/_app/verkaufsmengen'
      path: '/verkaufsmengen'
      fullPath: '/verkaufsmengen'
      preLoaderRoute: typeof AuthenticatedAppVerkaufsmengenRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/einstellungen/': {
      id: '/_authenticated/_app/einstellungen/'
      path: '/einstellungen'
      fullPath: '/einstellungen/'
      preLoaderRoute: typeof AuthenticatedAppEinstellungenIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/einstellungen/benutzer': {
      id: '/_authenticated/_app/einstellungen/benutzer'
      path: '/einstellungen/benutzer'
      fullPath: '/einstellungen/benutzer'
      preLoaderRoute: typeof AuthenticatedAppEinstellungenBenutzerRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/einstellungen/konfiguration': {
      id: '/_authenticated/_app/einstellungen/konfiguration'
      path: '/einstellungen/konfiguration'
      fullPath: '/einstellungen/konfiguration'
      preLoaderRoute: typeof AuthenticatedAppEinstellungenKonfigurationRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/gerichte/': {
      id: '/_authenticated/_app/gerichte/'
      path: '/gerichte'
      fullPath: '/gerichte/'
      preLoaderRoute: typeof AuthenticatedAppGerichteIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/gerichte/$dishId': {
      id: '/_authenticated/_app/gerichte/$dishId'
      path: '/gerichte/$dishId'
      fullPath: '/gerichte/$dishId'
      preLoaderRoute: typeof AuthenticatedAppGerichteDishIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/speisekarten/': {
      id: '/_authenticated/_app/speisekarten/'
      path: '/speisekarten'
      fullPath: '/speisekarten/'
      preLoaderRoute: typeof AuthenticatedAppSpeisekartenIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/speisekarten/$menuCardId': {
      id: '/_authenticated/_app/speisekarten/$menuCardId'
      path: '/speisekarten/$menuCardId'
      fullPath: '/speisekarten/$menuCardId'
      preLoaderRoute: typeof AuthenticatedAppSpeisekartenMenuCardIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/speisekarten/importieren': {
      id: '/_authenticated/_app/speisekarten/importieren'
      path: '/speisekarten/importieren'
      fullPath: '/speisekarten/importieren'
      preLoaderRoute: typeof AuthenticatedAppSpeisekartenImportierenRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/zutaten/': {
      id: '/_authenticated/_app/zutaten/'
      path: '/zutaten'
      fullPath: '/zutaten/'
      preLoaderRoute: typeof AuthenticatedAppZutatenIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/zutaten/importieren': {
      id: '/_authenticated/_app/zutaten/importieren'
      path: '/zutaten/importieren'
      fullPath: '/zutaten/importieren'
      preLoaderRoute: typeof AuthenticatedAppZutatenImportierenRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/gerichte/add-ons/': {
      id: '/_authenticated/_app/gerichte/add-ons/'
      path: '/gerichte/add-ons'
      fullPath: '/gerichte/add-ons/'
      preLoaderRoute: typeof AuthenticatedAppGerichteAddOnsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/gerichte/add-ons/$addOnId': {
      id: '/_authenticated/_app/gerichte/add-ons/$addOnId'
      path: '/gerichte/add-ons/$addOnId'
      fullPath: '/gerichte/add-ons/$addOnId'
      preLoaderRoute: typeof AuthenticatedAppGerichteAddOnsAddOnIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppSzenarioRoute: typeof AuthenticatedAppSzenarioRoute
  AuthenticatedAppUebersichtRoute: typeof AuthenticatedAppUebersichtRoute
  AuthenticatedAppVerkaufsmengenRoute: typeof AuthenticatedAppVerkaufsmengenRoute
  AuthenticatedAppEinstellungenBenutzerRoute: typeof AuthenticatedAppEinstellungenBenutzerRoute
  AuthenticatedAppEinstellungenKonfigurationRoute: typeof AuthenticatedAppEinstellungenKonfigurationRoute
  AuthenticatedAppGerichteDishIdRoute: typeof AuthenticatedAppGerichteDishIdRoute
  AuthenticatedAppSpeisekartenMenuCardIdRoute: typeof AuthenticatedAppSpeisekartenMenuCardIdRoute
  AuthenticatedAppSpeisekartenImportierenRoute: typeof AuthenticatedAppSpeisekartenImportierenRoute
  AuthenticatedAppZutatenImportierenRoute: typeof AuthenticatedAppZutatenImportierenRoute
  AuthenticatedAppEinstellungenIndexRoute: typeof AuthenticatedAppEinstellungenIndexRoute
  AuthenticatedAppGerichteIndexRoute: typeof AuthenticatedAppGerichteIndexRoute
  AuthenticatedAppSpeisekartenIndexRoute: typeof AuthenticatedAppSpeisekartenIndexRoute
  AuthenticatedAppZutatenIndexRoute: typeof AuthenticatedAppZutatenIndexRoute
  AuthenticatedAppGerichteAddOnsAddOnIdRoute: typeof AuthenticatedAppGerichteAddOnsAddOnIdRoute
  AuthenticatedAppGerichteAddOnsIndexRoute: typeof AuthenticatedAppGerichteAddOnsIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppSzenarioRoute: AuthenticatedAppSzenarioRoute,
  AuthenticatedAppUebersichtRoute: AuthenticatedAppUebersichtRoute,
  AuthenticatedAppVerkaufsmengenRoute: AuthenticatedAppVerkaufsmengenRoute,
  AuthenticatedAppEinstellungenBenutzerRoute:
    AuthenticatedAppEinstellungenBenutzerRoute,
  AuthenticatedAppEinstellungenKonfigurationRoute:
    AuthenticatedAppEinstellungenKonfigurationRoute,
  AuthenticatedAppGerichteDishIdRoute: AuthenticatedAppGerichteDishIdRoute,
  AuthenticatedAppSpeisekartenMenuCardIdRoute:
    AuthenticatedAppSpeisekartenMenuCardIdRoute,
  AuthenticatedAppSpeisekartenImportierenRoute:
    AuthenticatedAppSpeisekartenImportierenRoute,
  AuthenticatedAppZutatenImportierenRoute:
    AuthenticatedAppZutatenImportierenRoute,
  AuthenticatedAppEinstellungenIndexRoute:
    AuthenticatedAppEinstellungenIndexRoute,
  AuthenticatedAppGerichteIndexRoute: AuthenticatedAppGerichteIndexRoute,
  AuthenticatedAppSpeisekartenIndexRoute:
    AuthenticatedAppSpeisekartenIndexRoute,
  AuthenticatedAppZutatenIndexRoute: AuthenticatedAppZutatenIndexRoute,
  AuthenticatedAppGerichteAddOnsAddOnIdRoute:
    AuthenticatedAppGerichteAddOnsAddOnIdRoute,
  AuthenticatedAppGerichteAddOnsIndexRoute:
    AuthenticatedAppGerichteAddOnsIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedPasswortAendernRoute: typeof AuthenticatedPasswortAendernRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedPasswortAendernRoute: AuthenticatedPasswortAendernRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
